# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gpc < Formula
  desc "gpc is cli tool to create any page you want anywhere in confluence"
  homepage ""
  version "0.3.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/fchimpan/gpc/releases/download/v0.3.0/gpc_0.3.0_Darwin_arm64.tar.gz"
      sha256 "76fa6fb38aaa80ccb389662968edee99af8fff497e01c1b9beb930de4625a7d6"

      def install
        bin.install "gpc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/fchimpan/gpc/releases/download/v0.3.0/gpc_0.3.0_Darwin_x86_64.tar.gz"
      sha256 "c87aca06f08c4318958a227a6aa9e507855fd0cd99d40f69c03ff4f1afbb725a"

      def install
        bin.install "gpc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/fchimpan/gpc/releases/download/v0.3.0/gpc_0.3.0_Linux_x86_64.tar.gz"
      sha256 "751ec1cf16b994ef78809e306a37b9100ceb167dcca0974ef9f34cf5e7e5f7ab"

      def install
        bin.install "gpc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fchimpan/gpc/releases/download/v0.3.0/gpc_0.3.0_Linux_arm64.tar.gz"
      sha256 "5ae0fecd04301c39951c84d0dda0ae82badf4f76c1e632157510fd536d0828f9"

      def install
        bin.install "gpc"
      end
    end
  end
end
