# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gpc < Formula
  desc "gpc is cli tool to create any page you want anywhere in confluence"
  homepage ""
  version "0.4.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/fchimpan/gpc/releases/download/v0.4.1/gpc_0.4.1_Darwin_arm64.tar.gz"
      sha256 "d2bb493242e6f26c20158a0efa17bf8405668644e19b815f715f841bc01c0208"

      def install
        bin.install "gpc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/fchimpan/gpc/releases/download/v0.4.1/gpc_0.4.1_Darwin_x86_64.tar.gz"
      sha256 "afb59fe105737bc94fa83399a6048268545c46625c79fc4f303a0bcb211b3996"

      def install
        bin.install "gpc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/fchimpan/gpc/releases/download/v0.4.1/gpc_0.4.1_Linux_x86_64.tar.gz"
      sha256 "cffbb69fe2d8b21f2b330dac56b8671ef3b85b2d2eba871a15a50b55f19c7076"

      def install
        bin.install "gpc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fchimpan/gpc/releases/download/v0.4.1/gpc_0.4.1_Linux_arm64.tar.gz"
      sha256 "2833ba65d7be11ed3ff79ddc34d6759782c325f2dafd40d31d387f5dc0196aae"

      def install
        bin.install "gpc"
      end
    end
  end
end
